### PR TITLE
reset dataset, only include LEX and manual edits

### PR DESCRIPTION
**Pull request by semio**
Current dataset is based on

- GW datapoints & datapoint-concepts and entities & entity-concepts from https://github.com/open-numbers/ddf--gapminder--geo_entity_domain
- lex from https://github.com/open-numbers/ddf--gapminder--life_expectancy
- manual edits for WS server

I have checked the datapoints and confirmed only `life_expectancy_years` have changed comparing to old GW. Also tested with Validation-ddf tool and passed.

### CODE REVIEW

**Comment by jheeffer** [comment]
@semio I guess you didn't use the entities from https://github.com/open-numbers/ddf--gapminder--geo_entity_domain because they're old. What did you use as the source for the entities? We need to update that open-numbers repo.

**Comment by semio** [comment]
@jheeffer I am using my fork https://github.com/semio/ddf--gapminder--geo_entity_domain but it's identical to open-numbers for now. Which file in open-number's repo did you found it's old? 

I guess it's about some manual edits. Here is a list of changes I include in SG but not here:

- add `rank` column
- rename geographic_regions to world_6region, add ddf--entities--geo--world_6region.csv

**Comment by jheeffer** [comment]
in systema globalis we have for example world_6region and world_4region while in https://github.com/semio/ddf--gapminder--geo_entity_domain
we have world_4region, geographic_regions and geographic_regions_in_4_colors.

That indicates to me it's old files?

**Comment by semio** [comment]
Yes, that's the edit I only included in SG, but not in geo domain repo. 

I should update the geo domain repo using the geo entities in current SG right? How about the `rank` column? If it's only for sorting in WS server, I think we don't need to include it in geo domain?

**Comment by jheeffer** [comment]
Yes, the geo entities dataset is the source of truth for our geo-entities, so it should basically be a copy of what is in SG now (and then SG should get it from there). 

Even including `rank`. It actually is only really useful for `income_groups`, because these should be sorted by rank. Other entity sets shouldn't have `rank`, they have it because Angie looked for an easy way to order the mountainchart. But that means it's visualization specific and thus shouldn't be in the data. 
Until we find a better place it'll be in the data. But how do you enter the 'manual edits' to SG now? Where are they coming from/are they hardcoded?

**Comment by semio** [comment]
Sure, I will make the changes

for manual edits: check https://github.com/open-numbers/ddf--gapminder--systema_globalis/tree/master/etl/scripts/patches

If file name ends with '.0.csv', it is a new file added to the dataset; otherwise it's a diff for existing files (in daff diff format). I made the script to read them and apply to target files. But this only supports adding new files or modify existing files. If we are going to remove one file, we need to write another function in the script.

**Pull request merged**
